### ISSUE TITLE
Better Code Hub

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/guide#101]
Last week during ICTOpen, I spoke with someone from [SIG](https://www.sig.eu/) (software improvement group, not special interest group). They've developed their *The 10 Guidelines for Maintainable Software*, and have [tool](https://bettercodehub.com/) which checks your github repo to assess how maintainable id your code.

It looks interesting -- maybe it is just yet another code quality tool. But maybe it is worth checking it out! If it turns out to be quite good, maybe we can include it in the guide?

**Comment by LourensVeen** [comment]
Nice, I like these ten guidelines a lot; they're more high-level architectural aspects rather than the usual linting fare. Although when I tried it on my repo, the analysis seems a bit simplistic in some cases. And it fails me on not keeping my unit interfaces small, but that's mainly in generated code :-).

Disclaimer: not entirely unbiased, as SIG reviewed the NDFF architecture and backed me up on it after there were some issues :-).

**Comment by sverhoeven** [comment]
The service at https://bettercodehub.com/ requires write permission on your GitHub repositories including the code. In their [terms](https://bettercodehub.com/docs/terms-of-service) they promise to only make a copy of the code.  

Think carefully before granting the permission.

**Comment by nielsdrost** [comment]
So why to they need write permission then? Perhaps submit an issue?

**Comment by sverhoeven** [comment]
For setting up webhooks see https://bettercodehub.com/docs/faq question 4.4.

**Comment by bouweandela** [comment]
This content would be more appropriate for [The Turing Way](https://the-turing-way.netlify.app/index.html)
