### ISSUE TITLE
Twitter as community engagement tool

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/guide#242]
Tweeting new releases of software is a nice way to engage (potential) users. It @egpbos words "makes the project feel a lot more alive". Perhaps the guide should include (or point to) guidance on how to do this.

[Github-Twittction](https://github.com/m1ner79/Github-Twittction) can be used for this purpose (example [workflow](https://github.com/CLARIAH/grlc/blob/master/.github/workflows/tweet-release.yml) and [resulting tweet](https://twitter.com/grlcldapi/status/1328432868167565312)).

**Comment by PabRod** [comment]
Automation is great, but in order to get the most out of Twitter, I would suggest to keep an eye on the communities that can be interested in our software. 

Here are some things I've learned, particularly, collaborating with the `R` community via Twitter:

- Use (gently) the hashtag [#rstats](https://twitter.com/search?q=%23rstats&src=hashtag_click) for anything interesting to the R community.
- Pro-tip: try to get your blog approved in [R-bloggers](https://twitter.com/rbloggers)*. It means an **automatic** retweet to ~90.000 highly motivated potential users.

I am sure there exist similar Twitter communities around other languages.

*: see conditions, some of them negotiable, [here](https://www.r-bloggers.com/add-your-blog/).

**Comment by c-martinez** [comment]
Absolutely right @PabRod -- probably we should include what you say in whichever section of the guide/Turing way where we want to fit this in.

**Comment by egpbos** [comment]
Yes, I think a general "community engagement" chapter would be nice, with tips like this, maybe also blog writing tips, but also ways to automate parts of it.

**Comment by PabRod** [comment]
I agree with @egpbos. Let's talk about it.

## Possible reference

If I remember properly, there was a chapter about community engagement via social networks in Jeffrey Leek's _How to be a modern scientist_. The book is available [here](https://leanpub.com/modernscientist) for, literally, any price you want to pay for it (including 0.0 €).

**Comment by egpbos** [comment]
Interesting reference! The blogging and social media parts are definitely useful. And it's really helpful that this is written from a scientist point of view. The other point of view that should be added imho is the developer one. I'm sure many people have written about this as well (in blogs mostly, I guess). Main points from that perspective that I miss in the scientist one are (how) to promote releases (incl demos, gifs, etc), how to engage with general coding communities or specific project communities for help (but simultaneously to profile yourself as an active user / community member) and that you should definitely use Reddit as well. I think Twitter is indeed more important in (some) academic circles, but I've gotten a lot of useful coding feedback from Reddit.

**Comment by bouweandela** [comment]
This would be more suitable content for The Turing Way.
