### ISSUE TITLE
Explain that you are allowed to have GPL code as dependency

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#79]
(for Apache 2.0 code)

**Comment by LourensVeen** [comment]
More generally, there should be as many specific rules as we can give for licensing stuff. In this particular case, that we think it's fine to distribute our source code under ALv2 if it has a GPL dependency that isn't distributed along with it.

**Comment by LourensVeen** [comment]
Well, the situation is that Rob and I agree on this, and Niels has a different opinion. I'm the licensing guy, Rob is the final authority, and Niels apparently will keep arguing this until the heat death of the universe. I'm sick of arguing, so whatever, I'm done with this topic.

**Comment by bouweandela** [comment]
Just to make sure I do not give you the wrong impression: Niels was also tired of this issue and prepared to have anything in the guide just to be done with it, the decision to do a partial merge was purely mine.

I felt that the content of the section was good and that it was a waste not to merge the pull request as soon as possible, just because one of the licenses mentioned in there sparked some controversy. That's why I did the partial merge that included only the things that everyone seems to agree on.

Let's talk on Thursday to see if we can find a way forward in which everyone feels heard and we also provide the best possible information to the scientific community.

**Comment by bouweandela** [comment]
Some links on this topic:
https://www.gnu.org/licenses/license-list.en.html#apache2
https://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL
https://www.apache.org/licenses/GPL-compatibility.html

**Comment by bouweandela** [comment]
Generally, it would be nice if we could provide a reference to an authoritative third party when providing advice an a topic that could be perceived as controversial.

**Comment by bouweandela** [comment]
This content would be more appropriate for The Turing Way
