### ISSUE TITLE
Too many options for "GitHub add-ons" in Code Review section

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#86]
There are 13 options listed for "GitHub Add ons" in the Code Review section.

This is too many. Could we limit the selection to things we have experience with and that work well?

**Comment by LourensVeen** [comment]
Sure, just delete all of them! I did a survey last spring, but didn't try any because Lars B. didn't want to. So I put the results in the guide, hoping that whoever would do a code review next would try one and update the chapter. I guess no one did, and now that list is probably hopelessly outdated.

Also, Github now has code review functionality built in, so that should probably be the first choice unless it turns out to be deficient somehow. Shall I just remove the whole thing and suggest people use  Github?

**Comment by nielsdrost** [comment]
Good plan! I think GitHub should cover all of our Code Review needs for now, since "keep it simple" is our current Code Review Motto :-)
